# -*- coding: utf-8 -*-
"""EVD_200ITEMS_PART2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMTLZSCqvel7gqWgJQJjAu-cSkP7tO-q
"""

!pip -q install -U "transformers>=4.50.0" accelerate bitsandbytes sentencepiece "pandas==2.2.2" huggingface_hub

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True,max_split_size_mb:256"

import re
import getpass
import torch
import torch.nn.functional as F
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from huggingface_hub import login
from google.colab import files


if not torch.cuda.is_available():
    raise RuntimeError("No GPU detected. In Colab: Runtime > Change runtime type > GPU, then re-run.")

props = torch.cuda.get_device_properties(0)
total_gb = props.total_memory / (1024**3)
print("GPU:", props.name)
print("GPU VRAM (GiB):", round(total_gb, 2))
major, minor = torch.cuda.get_device_capability()
print("Compute capability:", (major, minor))
torch.backends.cuda.matmul.allow_tf32 = True

def pick_compute_dtype():
    major, _ = torch.cuda.get_device_capability()
    return torch.bfloat16 if major >= 8 else torch.float16

COMPUTE_DTYPE = pick_compute_dtype()
print("Compute dtype:", COMPUTE_DTYPE)

gpu_budget = max(int(total_gb - (6 if total_gb <= 24 else 4)), 10)
MAX_MEMORY = {0: f"{gpu_budget}GiB", "cpu": "240GiB"}
print("max_memory:", MAX_MEMORY)


HF_TOKEN = None
try:
    from google.colab import userdata
    HF_TOKEN = userdata.get("HF_TOKEN")
except Exception:
    HF_TOKEN = None

if not HF_TOKEN:
    HF_TOKEN = getpass.getpass("Paste your HF token (hf_...): ")

login(token=HF_TOKEN)


print("\nUpload your CSV")
uploaded = files.upload()
if not uploaded:
    raise RuntimeError("No file uploaded.")
CSV_PATH = list(uploaded.keys())[0]
print("Using:", CSV_PATH)


MODEL_NAME = "google/gemma-3-27b-it"
OUT_PATH = "lm_logprob_results_high_low_gemma3_27b_it_c_and_f_nopunct.csv"

SENT_COL = "Sentence"
COND_COL = "Condition"
FILTER_TO_HIGH_LOW = True
STRICT_VERB_MAP = False
LOAD_IN_4BIT = True


VERB_MAP = {
    "alımlar": ("başladı", "başlamış"),
    "antibiyotikler": ("tükendi", "tükenmiş"),
    "ataması": ("açıklandı", "açıklanmış"),
    "bakiyesi": ("bitti", "bitmiş"),
    "bankacılık": ("düzeldi", "düzelmiş"),
    "baskı": ("geldi", "gelmiş"),
    "basıncı": ("düştü", "düşmüş"),
    "belli": ("oldu", "olmuş"),
    "biletleri": ("tükendi", "tükenmiş"),
    "bölümü": ("sızdı", "sızmış"),
    "dağıtıma": ("çıktı", "çıkmış"),
    "değişimi": ("onaylandı", "onaylanmış"),
    "dosyalar": ("silindi", "silinmiş"),
    "durumu": ("değişti", "değişmiş"),
    "dün": ("başladı", "başlamış"),
    "ekip": ("büyüdü", "büyümüş"),
    "elektrikleri": ("kesildi", "kesilmiş"),
    "fiyatı": ("arttı", "artmış"),
    "fırtına": ("başladı", "başlamış"),
    "geri": ("çekildi", "çekilmiş"),
    "görüşmelere": ("başlandı", "başlanmış"),
    "gözetmenleri": ("değişti", "değişmiş"),
    "gücü": ("azaltıldı", "azaltılmış"),
    "hata": ("düzeltildi", "düzeltilmiş"),
    "hesaplar": ("kilitlendi", "kilitlenmiş"),
    "ihaleyi": ("kazandı", "kazanmış"),
    "ilan": ("edildi", "edilmiş"),
    "ilaçlama": ("yapıldı", "yapılmış"),
    "indirim": ("uzadı", "uzamış"),
    "indirimler": ("başladı", "başlamış"),
    "internet": ("gitti", "gitmiş"),
    "iptal": ("edildi", "edilmiş"),
    "istifa": ("etti", "etmiş"),
    "istifası": ("duyuruldu", "duyurulmuş"),
    "işlemcisini": ("değiştirdi", "değiştirmiş"),
    "kadro": ("netleşti", "netleşmiş"),
    "kapılar": ("açıldı", "açılmış"),
    "kart": ("çıktı", "çıkmış"),
    "kayıtları": ("uzatıldı", "uzatılmış"),
    "kesintisi": ("başladı", "başlamış"),
    "kullanımı": ("yasaklandı", "yasaklanmış"),
    "maaşlar": ("yattı", "yatmış"),
    "noktaları": ("kaldırıldı", "kaldırılmış"),
    "oranı": ("yükseldi", "yükselmiş"),
    "otobüsü": ("kalktı", "kalkmış"),
    "payı": ("arttı", "artmış"),
    "perona": ("girdi", "girmiş"),
    "primler": ("yatırıldı", "yatırılmış"),
    "programı": ("açıklandı", "açıklanmış"),
    "projesi": ("onaylandı", "onaylanmış"),
    "randevuları": ("açıldı", "açılmış"),
    "raporu": ("yayınlandı", "yayınlanmış"),
    "rötar": ("yaptı", "yapmış"),
    "saati": ("değişti", "değişmiş"),
    "saatleri": ("değişti", "değişmiş"),
    "sakatlığı": ("uzadı", "uzamış"),
    "sanatçı": ("gelmedi", "gelmemiş"),
    "sarsıntılar": ("azaldı", "azalmış"),
    "sayım": ("başladı", "başlamış"),
    "seansı": ("eklendi", "eklenmiş"),
    "seferler": ("aksadı", "aksamış"),
    "sonuçları": ("açıklandı", "açıklanmış"),
    "stokları": ("bitti", "bitmiş"),
    "stoğu": ("geldi", "gelmiş"),
    "sular": ("kesildi", "kesilmiş"),
    "sunucular": ("çöktü", "çökmüş"),
    "sınav": ("ertelendi", "ertelenmiş"),
    "sınıfı": ("değişti", "değişmiş"),
    "tarihe": ("ertelendi", "ertelenmiş"),
    "tarihi": ("ertelendi", "ertelenmiş"),
    "trafiğe": ("kapandı", "kapanmış"),
    "tünel": ("kapatıldı", "kapatılmış"),
    "uygulama": ("güncellendi", "güncellenmiş"),
    "uçağı": ("gecikti", "gecikmiş"),
    "yasağı": ("kalktı", "kalkmış"),
    "yayın": ("açıldı", "açılmış"),
    "yağışı": ("yaklaştı", "yaklaşmış"),
    "zam": ("geldi", "gelmiş"),
    "zorunluluğu": ("kalktı", "kalkmış"),
    "özellik": ("geldi", "gelmiş"),
    "ücreti": ("arttı", "artmış"),
    "ücretleri": ("arttı", "artmış"),
}


def split_on_blank(sentence: str):
    s = str(sentence)
    m = re.search(r"_{2,}", s)
    if not m:
        return None, None
    return s[:m.start()], s[m.end():]

def _clean_last_word(pre_text: str) -> str:
    clean = re.sub(r"[^\w\s]", "", str(pre_text)).strip()
    if not clean:
        return ""
    return clean.split()[-1].lower()

def get_candidates_from_verbmap(prompt_left: str):
    last_word = _clean_last_word(prompt_left)
    if last_word in VERB_MAP:
        c1, c2 = VERB_MAP[last_word]
        return c1, c2, last_word, True
    return "edildi", "edilmiş", last_word, False

def insert_candidate(prompt_left: str, candidate: str) -> str:
    candidate = str(candidate).strip()
    if prompt_left and not prompt_left.endswith((" ", "\t", "\n")):
        return " " + candidate
    return candidate

def choice_from_delta(delta: float) -> str:
    if delta > 0: return "DI"
    if delta < 0: return "MIŞ"
    return "TIE"

def _shift_trailing_ws(prompt: str, continuation: str):
    m = re.search(r"\s*$", prompt)
    trail = m.group(0) if m else ""
    if trail:
        return prompt[:-len(trail)], trail + continuation
    return prompt, continuation

def strip_leading_punct(s: str) -> str:
    return re.sub(r"^\s*[.?!,;:]+\s*", "", str(s))

def attach_suffix_no_punct(continuation: str, suffix_right: str) -> str:
    suf = strip_leading_punct(suffix_right).strip()
    if not suf:
        return continuation
    return continuation + " " + suf


print("\nLoading model:", MODEL_NAME)
os.makedirs("offload", exist_ok=True)

try:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, token=HF_TOKEN, use_fast=True)
except Exception as e:
    print("Fast tokenizer failed, falling back to slow tokenizer. Error:", repr(e))
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, token=HF_TOKEN, use_fast=False)

if tokenizer.pad_token is None and tokenizer.eos_token is not None:
    tokenizer.pad_token = tokenizer.eos_token

load_kwargs = dict(
    device_map="auto",
    low_cpu_mem_usage=True,
    max_memory=MAX_MEMORY,
    offload_folder="offload",
    offload_state_dict=True,
    attn_implementation="sdpa",
)

if LOAD_IN_4BIT:
    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=COMPUTE_DTYPE,
    )
    load_kwargs["quantization_config"] = quant_config
    load_kwargs["torch_dtype"] = COMPUTE_DTYPE
else:
    load_kwargs["torch_dtype"] = COMPUTE_DTYPE

model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, token=HF_TOKEN, **load_kwargs)
model.eval()

MODEL_DEVICE = next(model.parameters()).device
print("Model loaded.")
print("4-bit:", LOAD_IN_4BIT)
print("Model device:", MODEL_DEVICE)


@torch.inference_mode()
def logprob_continuation(prompt: str, continuation: str):
    """
    Returns: sum_logp, mean_logp, n_tokens, prefix_ok
    Scores EXACT prompt+continuation.
    """
    prompt2, cont2 = _shift_trailing_ws(prompt, continuation)
    full = prompt2 + cont2

    enc_full = tokenizer(full, return_tensors="pt", add_special_tokens=False)
    enc_prompt = tokenizer(prompt2, return_tensors="pt", add_special_tokens=False)

    full_ids = enc_full.input_ids[0]
    prompt_ids = enc_prompt.input_ids[0]
    prefix_ok = bool(torch.equal(full_ids[:len(prompt_ids)], prompt_ids))

    prompt_len = len(prompt_ids)
    cont_ids = full_ids[prompt_len:]
    n = len(cont_ids)
    if n == 0 or prompt_len == 0:
        return float("-inf"), float("-inf"), 0, prefix_ok

    input_ids = enc_full.input_ids.to(MODEL_DEVICE)
    attention_mask = enc_full.attention_mask.to(MODEL_DEVICE)

    logits = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False).logits[0]
    logprobs = F.log_softmax(logits, dim=-1)

    start = prompt_len - 1
    end = start + n
    lp_slice = logprobs[start:end]

    cont_ids_dev = cont_ids.to(MODEL_DEVICE)
    token_logps = lp_slice.gather(1, cont_ids_dev.unsqueeze(1)).squeeze(1)

    sum_logp = float(token_logps.sum().item())
    mean_logp = sum_logp / n
    return sum_logp, mean_logp, n, prefix_ok

def score_item(prompt_left: str, suffix_right: str, cand_di: str, cand_mis: str):
    """
    c: candidate-only (primary)
    f: candidate+suffix with leading punctuation removed (robustness)
    """
    di_ins = insert_candidate(prompt_left, cand_di)
    mis_ins = insert_candidate(prompt_left, cand_mis)

    # c) candidate-only
    di_c_sum, di_c_mean, di_c_n, di_c_ok = logprob_continuation(prompt_left, di_ins)
    mi_c_sum, mi_c_mean, mi_c_n, mi_c_ok = logprob_continuation(prompt_left, mis_ins)

    # f) candidate + suffix (no leading punctuation)
    suffix_stripped = strip_leading_punct(suffix_right)
    di_full = attach_suffix_no_punct(di_ins, suffix_right)
    mi_full = attach_suffix_no_punct(mis_ins, suffix_right)

    di_f_sum, di_f_mean, di_f_n, di_f_ok = logprob_continuation(prompt_left, di_full)
    mi_f_sum, mi_f_mean, mi_f_n, mi_f_ok = logprob_continuation(prompt_left, mi_full)

    delta_c_mean = di_c_mean - mi_c_mean
    delta_f_mean = di_f_mean - mi_f_mean

    return {
        "Used_Insert_DI": di_ins,
        "Used_Insert_MIS": mis_ins,
        "suffix_right_stripped": suffix_stripped,

        "di_c_sum": di_c_sum, "di_c_mean": di_c_mean, "di_c_n_tok": di_c_n, "di_c_prefix_ok": di_c_ok,
        "mis_c_sum": mi_c_sum, "mis_c_mean": mi_c_mean, "mis_c_n_tok": mi_c_n, "mis_c_prefix_ok": mi_c_ok,
        "delta_c_sum": di_c_sum - mi_c_sum,
        "delta_c_mean": delta_c_mean,
        "choice_c_mean": choice_from_delta(delta_c_mean),

        "di_f_sum": di_f_sum, "di_f_mean": di_f_mean, "di_f_n_tok": di_f_n, "di_f_prefix_ok": di_f_ok,
        "mis_f_sum": mi_f_sum, "mis_f_mean": mi_f_mean, "mis_f_n_tok": mi_f_n, "mis_f_prefix_ok": mi_f_ok,
        "delta_f_sum": di_f_sum - mi_f_sum,
        "delta_f_mean": delta_f_mean,
        "choice_f_mean": choice_from_delta(delta_f_mean),
    }


df = pd.read_csv(CSV_PATH)
if SENT_COL not in df.columns or COND_COL not in df.columns:
    raise ValueError(f"CSV must contain '{SENT_COL}' and '{COND_COL}' columns.")

df[COND_COL] = df[COND_COL].astype(str).str.strip()

if FILTER_TO_HIGH_LOW:
    df = df[df[COND_COL].str.lower().isin(["high", "low"])].reset_index(drop=True)
    df[COND_COL] = df[COND_COL].str.capitalize()

print("\nRows to score:", len(df))

missing_keys = []
for s in df[SENT_COL].astype(str):
    left, _ = split_on_blank(s)
    if left is None:
        continue
    lw = _clean_last_word(left)
    if lw and lw not in VERB_MAP:
        missing_keys.append(lw)

if missing_keys:
    print("\nWARNING: Some last_word values are not in VERB_MAP:")
    print(pd.Series(missing_keys).value_counts())
else:
    print("\nOK: VERB_MAP covers High/Low items.")


results = []
skipped_no_blank = 0
skipped_no_map = 0

for i, row in df.iterrows():
    sent = row[SENT_COL]
    cond = row.get(COND_COL, "Unknown")

    left, right = split_on_blank(sent)
    if left is None:
        skipped_no_blank += 1
        continue

    cand_di, cand_mis, last_word, map_hit = get_candidates_from_verbmap(left)
    if STRICT_VERB_MAP and (not map_hit):
        skipped_no_map += 1
        continue

    sc = score_item(left, right, cand_di, cand_mis)

    results.append({
        "row_id": i,
        "Condition": cond,
        "Sentence_raw": str(sent),
        "prompt_left": left,
        "suffix_right_raw": right,
        "last_word": last_word,
        "verb_map_hit": map_hit,
        "Used_Verb_DI": cand_di,
        "Used_Verb_MIS": cand_mis,
        **sc
    })

out_df = pd.DataFrame(results)
out_df.to_csv(OUT_PATH, index=False, encoding="utf-8-sig")

print("\nDone. Saved:", OUT_PATH)
print("Skipped (no blank):", skipped_no_blank)
print("Skipped (no map; STRICT_VERB_MAP=True):", skipped_no_map)

print("\n== Mean deltas by Condition ==")
print(out_df.groupby("Condition")[["delta_c_mean", "delta_f_mean"]].mean())

print("\n== Choice counts (candidate-only) ==")
print(out_df.groupby("Condition")["choice_c_mean"].value_counts())

print("\n== Choice counts (candidate+suffix, NO leading punct) ==")
print(out_df.groupby("Condition")["choice_f_mean"].value_counts())

g = out_df.groupby("Condition")[["delta_c_mean", "delta_f_mean"]].mean()
if ("High" in g.index) and ("Low" in g.index):
    print("\n*** TRUST EFFECT (High - Low) ***")
    print(f"candidate-only            (delta_c_mean): {g.loc['High','delta_c_mean'] - g.loc['Low','delta_c_mean']:.4f}")
    print(f"candidate+suffix NO PUNCT (delta_f_mean): {g.loc['High','delta_f_mean'] - g.loc['Low','delta_f_mean']:.4f}")

prefix_cols = ["di_c_prefix_ok","mis_c_prefix_ok","di_f_prefix_ok","mis_f_prefix_ok"]
mismatch_rate = 1.0 - out_df[prefix_cols].astype(bool).mean()
print("\n== Prefix mismatch rates (should be near 0) ==")
print(mismatch_rate)

files.download(OUT_PATH)

# =========================
# COLAB: DI vs MIŞ scoring with Trendyol/Trendyol-LLM-7b-base-v1.0 (4-bit)
# MOST SCIENTIFIC VERSION:
#   - c = candidate-only (primary; DI vs MIŞ on the verb itself)
#   - f = candidate + suffix_right with LEADING PUNCTUATION REMOVED (so '.' is never scored)
#   - If suffix_right is only '.', then f == c (sanity check)
# =========================

!pip -q install -U transformers accelerate bitsandbytes sentencepiece

import re
import torch
import torch.nn.functional as F
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from google.colab import files

# -------------------------
# 0) GPU check
# -------------------------
if not torch.cuda.is_available():
    raise RuntimeError(
        "No GPU detected. In Colab: Runtime > Change runtime type > GPU, then re-run."
    )

torch.backends.cuda.matmul.allow_tf32 = True

def pick_compute_dtype():
    major, minor = torch.cuda.get_device_capability()
    return torch.bfloat16 if major >= 8 else torch.float16

COMPUTE_DTYPE = pick_compute_dtype()
print("GPU:", torch.cuda.get_device_name(0))
print("Compute dtype:", COMPUTE_DTYPE)

# -------------------------
# 1) Upload CSV
# -------------------------
print("Upload your CSV (must include 'Sentence' and 'Condition' columns)")
uploaded = files.upload()
if not uploaded:
    raise RuntimeError("No file uploaded.")
CSV_PATH = list(uploaded.keys())[0]
print("Using:", CSV_PATH)

# -------------------------
# 2) Config
# -------------------------
MODEL_NAME = "Trendyol/Trendyol-LLM-7b-base-v1.0"
OUT_PATH = "lm_logprob_results_high_low_trendyol_llm_7b_base_v1_0_c_and_f_nopunct.csv"

SENT_COL = "Sentence"
COND_COL = "Condition"

FILTER_TO_HIGH_LOW = True
STRICT_VERB_MAP = False  # True => skip items whose last_word isn't in VERB_MAP

LOAD_IN_4BIT = True

# -------------------------
# 3) Verb map (UPDATED for 100-per-condition set)
# -------------------------
VERB_MAP = {
    "alımlar": ("başladı", "başlamış"),
    "antibiyotikler": ("tükendi", "tükenmiş"),
    "ataması": ("açıklandı", "açıklanmış"),
    "bakiyesi": ("bitti", "bitmiş"),
    "bankacılık": ("düzeldi", "düzelmiş"),
    "baskı": ("geldi", "gelmiş"),
    "basıncı": ("düştü", "düşmüş"),
    "belli": ("oldu", "olmuş"),
    "biletleri": ("tükendi", "tükenmiş"),
    "bölümü": ("sızdı", "sızmış"),
    "dağıtıma": ("çıktı", "çıkmış"),
    "değişimi": ("onaylandı", "onaylanmış"),
    "dosyalar": ("silindi", "silinmiş"),
    "durumu": ("değişti", "değişmiş"),
    "dün": ("başladı", "başlamış"),
    "ekip": ("büyüdü", "büyümüş"),
    "elektrikleri": ("kesildi", "kesilmiş"),
    "fiyatı": ("arttı", "artmış"),
    "fırtına": ("başladı", "başlamış"),
    "geri": ("çekildi", "çekilmiş"),
    "görüşmelere": ("başlandı", "başlanmış"),
    "gözetmenleri": ("değişti", "değişmiş"),
    "gücü": ("azaltıldı", "azaltılmış"),
    "hata": ("düzeltildi", "düzeltilmiş"),
    "hesaplar": ("kilitlendi", "kilitlenmiş"),
    "ihaleyi": ("kazandı", "kazanmış"),
    "ilan": ("edildi", "edilmiş"),
    "ilaçlama": ("yapıldı", "yapılmış"),
    "indirim": ("uzadı", "uzamış"),
    "indirimler": ("başladı", "başlamış"),
    "internet": ("gitti", "gitmiş"),
    "iptal": ("edildi", "edilmiş"),
    "istifa": ("etti", "etmiş"),
    "istifası": ("duyuruldu", "duyurulmuş"),
    "işlemcisini": ("değiştirdi", "değiştirmiş"),
    "kadro": ("netleşti", "netleşmiş"),
    "kapılar": ("açıldı", "açılmış"),
    "kart": ("çıktı", "çıkmış"),
    "kayıtları": ("uzatıldı", "uzatılmış"),
    "kesintisi": ("başladı", "başlamış"),
    "kullanımı": ("yasaklandı", "yasaklanmış"),
    "maaşlar": ("yattı", "yatmış"),
    "noktaları": ("kaldırıldı", "kaldırılmış"),
    "oranı": ("yükseldi", "yükselmiş"),
    "otobüsü": ("kalktı", "kalkmış"),
    "payı": ("arttı", "artmış"),
    "perona": ("girdi", "girmiş"),
    "primler": ("yatırıldı", "yatırılmış"),
    "programı": ("açıklandı", "açıklanmış"),
    "projesi": ("onaylandı", "onaylanmış"),
    "randevuları": ("açıldı", "açılmış"),
    "raporu": ("yayınlandı", "yayınlanmış"),
    "rötar": ("yaptı", "yapmış"),
    "saati": ("değişti", "değişmiş"),
    "saatleri": ("değişti", "değişmiş"),
    "sakatlığı": ("uzadı", "uzamış"),
    "sanatçı": ("gelmedi", "gelmemiş"),
    "sarsıntılar": ("azaldı", "azalmış"),
    "sayım": ("başladı", "başlamış"),
    "seansı": ("eklendi", "eklenmiş"),
    "seferler": ("aksadı", "aksamış"),
    "sonuçları": ("açıklandı", "açıklanmış"),
    "stokları": ("bitti", "bitmiş"),
    "stoğu": ("geldi", "gelmiş"),
    "sular": ("kesildi", "kesilmiş"),
    "sunucular": ("çöktü", "çökmüş"),
    "sınav": ("ertelendi", "ertelenmiş"),
    "sınıfı": ("değişti", "değişmiş"),
    "tarihe": ("ertelendi", "ertelenmiş"),
    "tarihi": ("ertelendi", "ertelenmiş"),
    "trafiğe": ("kapandı", "kapanmış"),
    "tünel": ("kapatıldı", "kapatılmış"),
    "uygulama": ("güncellendi", "güncellenmiş"),
    "uçağı": ("gecikti", "gecikmiş"),
    "yasağı": ("kalktı", "kalkmış"),
    "yayın": ("açıldı", "açılmış"),
    "yağışı": ("yaklaştı", "yaklaşmış"),
    "zam": ("geldi", "gelmiş"),
    "zorunluluğu": ("kalktı", "kalkmış"),
    "özellik": ("geldi", "gelmiş"),
    "ücreti": ("arttı", "artmış"),
    "ücretleri": ("arttı", "artmış"),
}

# -------------------------
# 4) Helpers
# -------------------------
def split_on_blank(sentence: str):
    s = str(sentence)
    m = re.search(r"_{2,}", s)  # blank = __ or longer
    if not m:
        return None, None
    return s[:m.start()], s[m.end():]

def _clean_last_word(pre_text: str) -> str:
    clean = re.sub(r"[^\w\s]", "", str(pre_text)).strip()
    if not clean:
        return ""
    return clean.split()[-1].lower()

def get_candidates_from_verbmap(prompt_left: str):
    last_word = _clean_last_word(prompt_left)
    if last_word in VERB_MAP:
        c1, c2 = VERB_MAP[last_word]
        return c1, c2, last_word, True
    return "edildi", "edilmiş", last_word, False

def insert_candidate(prompt_left: str, candidate: str) -> str:
    candidate = str(candidate).strip()
    if prompt_left and not prompt_left.endswith((" ", "\t", "\n")):
        return " " + candidate
    return candidate

def choice_from_delta(delta: float) -> str:
    if delta > 0: return "DI"
    if delta < 0: return "MIŞ"
    return "TIE"

def _shift_trailing_ws(prompt: str, continuation: str):
    m = re.search(r"\s*$", prompt)
    trail = m.group(0) if m else ""
    if trail:
        return prompt[:-len(trail)], trail + continuation
    return prompt, continuation

def strip_leading_punct(s: str) -> str:
    # remove leading punctuation and surrounding whitespace
    return re.sub(r"^\s*[.?!,;:]+\s*", "", str(s))

def attach_suffix_no_punct(continuation: str, suffix_right: str) -> str:
    suf = strip_leading_punct(suffix_right).strip()
    if not suf:
        return continuation
    return continuation + " " + suf

# -------------------------
# 5) Load model + tokenizer
# -------------------------
print("Loading model:", MODEL_NAME)

try:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
except Exception as e:
    print("Fast tokenizer failed, falling back to slow tokenizer. Error:", repr(e))
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=False)

if tokenizer.pad_token is None and tokenizer.eos_token is not None:
    tokenizer.pad_token = tokenizer.eos_token

load_kwargs = dict(
    device_map="auto",
    torch_dtype=COMPUTE_DTYPE,
)

if LOAD_IN_4BIT:
    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=COMPUTE_DTYPE,
    )
    load_kwargs["quantization_config"] = quant_config

model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, **load_kwargs)
model.eval()

MODEL_DEVICE = next(model.parameters()).device
print("Model loaded.")
print("4-bit:", LOAD_IN_4BIT)
print("Model device:", MODEL_DEVICE)

# -------------------------
# 6) Logprob
# -------------------------
@torch.inference_mode()
def logprob_continuation(prompt: str, continuation: str):
    """
    Returns: sum_logp, mean_logp, n_tokens, prefix_ok
    Scores EXACT prompt+continuation.
    """
    prompt2, cont2 = _shift_trailing_ws(prompt, continuation)
    full = prompt2 + cont2

    enc_full = tokenizer(full, return_tensors="pt", add_special_tokens=False)
    enc_prompt = tokenizer(prompt2, return_tensors="pt", add_special_tokens=False)

    full_ids = enc_full.input_ids[0]
    prompt_ids = enc_prompt.input_ids[0]
    prefix_ok = bool(torch.equal(full_ids[:len(prompt_ids)], prompt_ids))

    prompt_len = len(prompt_ids)
    cont_ids = full_ids[prompt_len:]
    n = len(cont_ids)
    if n == 0 or prompt_len == 0:
        return float("-inf"), float("-inf"), 0, prefix_ok

    input_ids = enc_full.input_ids.to(MODEL_DEVICE)
    attention_mask = enc_full.attention_mask.to(MODEL_DEVICE)

    logits = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False).logits[0]
    logprobs = F.log_softmax(logits, dim=-1)

    start = prompt_len - 1
    end = start + n
    lp_slice = logprobs[start:end]

    cont_ids_dev = cont_ids.to(MODEL_DEVICE)
    token_logps = lp_slice.gather(1, cont_ids_dev.unsqueeze(1)).squeeze(1)

    sum_logp = float(token_logps.sum().item())
    mean_logp = sum_logp / n
    return sum_logp, mean_logp, n, prefix_ok

def score_item(prompt_left: str, suffix_right: str, cand_di: str, cand_mis: str):
    """
    c: candidate-only (primary)
    f: candidate+suffix with leading punctuation removed (robustness)
    """
    di_ins = insert_candidate(prompt_left, cand_di)
    mis_ins = insert_candidate(prompt_left, cand_mis)

    # c) candidate-only
    di_c_sum, di_c_mean, di_c_n, di_c_ok = logprob_continuation(prompt_left, di_ins)
    mi_c_sum, mi_c_mean, mi_c_n, mi_c_ok = logprob_continuation(prompt_left, mis_ins)

    # f) candidate + suffix (no leading punctuation)
    suffix_stripped = strip_leading_punct(suffix_right)
    di_full = attach_suffix_no_punct(di_ins, suffix_right)
    mi_full = attach_suffix_no_punct(mis_ins, suffix_right)

    di_f_sum, di_f_mean, di_f_n, di_f_ok = logprob_continuation(prompt_left, di_full)
    mi_f_sum, mi_f_mean, mi_f_n, mi_f_ok = logprob_continuation(prompt_left, mi_full)

    delta_c_mean = di_c_mean - mi_c_mean
    delta_f_mean = di_f_mean - mi_f_mean

    return {
        "Used_Insert_DI": di_ins,
        "Used_Insert_MIS": mis_ins,
        "suffix_right_stripped": suffix_stripped,

        "di_c_sum": di_c_sum, "di_c_mean": di_c_mean, "di_c_n_tok": di_c_n, "di_c_prefix_ok": di_c_ok,
        "mis_c_sum": mi_c_sum, "mis_c_mean": mi_c_mean, "mis_c_n_tok": mi_c_n, "mis_c_prefix_ok": mi_c_ok,
        "delta_c_sum": di_c_sum - mi_c_sum,
        "delta_c_mean": delta_c_mean,
        "choice_c_mean": choice_from_delta(delta_c_mean),

        "di_f_sum": di_f_sum, "di_f_mean": di_f_mean, "di_f_n_tok": di_f_n, "di_f_prefix_ok": di_f_ok,
        "mis_f_sum": mi_f_sum, "mis_f_mean": mi_f_mean, "mis_f_n_tok": mi_f_n, "mis_f_prefix_ok": mi_f_ok,
        "delta_f_sum": di_f_sum - mi_f_sum,
        "delta_f_mean": delta_f_mean,
        "choice_f_mean": choice_from_delta(delta_f_mean),
    }

# -------------------------
# 7) Read CSV + filter
# -------------------------
df = pd.read_csv(CSV_PATH)
if SENT_COL not in df.columns or COND_COL not in df.columns:
    raise ValueError(f"CSV must contain '{SENT_COL}' and '{COND_COL}' columns.")

df[COND_COL] = df[COND_COL].astype(str).str.strip()

if FILTER_TO_HIGH_LOW:
    df = df[df[COND_COL].str.lower().isin(["high", "low"])].reset_index(drop=True)
    df[COND_COL] = df[COND_COL].str.capitalize()

print("Rows to score:", len(df))

# Coverage check on High/Low
missing_keys = []
for s in df[SENT_COL].astype(str):
    left, _ = split_on_blank(s)
    if left is None:
        continue
    lw = _clean_last_word(left)
    if lw and lw not in VERB_MAP:
        missing_keys.append(lw)

if missing_keys:
    print("\nWARNING: Some last_word values are not in VERB_MAP:")
    print(pd.Series(missing_keys).value_counts())
else:
    print("\nOK: VERB_MAP covers High/Low items.")

# -------------------------
# 8) Loop
# -------------------------
results = []
skipped_no_blank = 0
skipped_no_map = 0

for i, row in df.iterrows():
    sent = row[SENT_COL]
    cond = row.get(COND_COL, "Unknown")

    left, right = split_on_blank(sent)
    if left is None:
        skipped_no_blank += 1
        continue

    cand_di, cand_mis, last_word, map_hit = get_candidates_from_verbmap(left)
    if STRICT_VERB_MAP and (not map_hit):
        skipped_no_map += 1
        continue

    sc = score_item(left, right, cand_di, cand_mis)

    results.append({
        "row_id": i,
        "Condition": cond,
        "Sentence_raw": str(sent),
        "prompt_left": left,
        "suffix_right_raw": right,
        "last_word": last_word,
        "verb_map_hit": map_hit,
        "Used_Verb_DI": cand_di,
        "Used_Verb_MIS": cand_mis,
        **sc
    })

out_df = pd.DataFrame(results)
out_df.to_csv(OUT_PATH, index=False, encoding="utf-8-sig")

print("\nDone. Saved:", OUT_PATH)
print("Skipped (no blank):", skipped_no_blank)
print("Skipped (no map; STRICT_VERB_MAP=True):", skipped_no_map)

# -------------------------
# 9) Summary
# -------------------------
print("\n== Mean deltas by Condition ==")
print(out_df.groupby("Condition")[["delta_c_mean", "delta_f_mean"]].mean())

print("\n== Choice counts (candidate-only) ==")
print(out_df.groupby("Condition")["choice_c_mean"].value_counts())

print("\n== Choice counts (candidate+suffix, NO leading punct) ==")
print(out_df.groupby("Condition")["choice_f_mean"].value_counts())

g = out_df.groupby("Condition")[["delta_c_mean", "delta_f_mean"]].mean()
if ("High" in g.index) and ("Low" in g.index):
    print("\n*** TRUST EFFECT (High - Low) ***")
    print(f"candidate-only            (delta_c_mean): {g.loc['High','delta_c_mean'] - g.loc['Low','delta_c_mean']:.4f}")
    print(f"candidate+suffix NO PUNCT (delta_f_mean): {g.loc['High','delta_f_mean'] - g.loc['Low','delta_f_mean']:.4f}")

prefix_cols = ["di_c_prefix_ok","mis_c_prefix_ok","di_f_prefix_ok","mis_f_prefix_ok"]
mismatch_rate = 1.0 - out_df[prefix_cols].astype(bool).mean()
print("\n== Prefix mismatch rates (should be near 0) ==")
print(mismatch_rate)

# -------------------------
# 10) Download output
# -------------------------
files.download(OUT_PATH)

# =========================
# COLAB: DI vs MIŞ scoring with Orbina/Orbita-v0.1 (4-bit)
# MOST SCIENTIFIC VERSION:
#   - c = candidate-only (primary; DI vs MIŞ on the verb itself)
#   - f = candidate + suffix_right with LEADING PUNCTUATION REMOVED (so '.' is never scored)
#   - If suffix_right is only '.', then f == c (sanity check)
# =========================

!pip -q install -U transformers accelerate bitsandbytes sentencepiece pandas

import re
import torch
import torch.nn.functional as F
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from google.colab import files

# -------------------------
# 0) GPU check
# -------------------------
if not torch.cuda.is_available():
    raise RuntimeError(
        "No GPU detected. In Colab: Runtime > Change runtime type > GPU, then re-run."
    )

torch.backends.cuda.matmul.allow_tf32 = True

def pick_compute_dtype():
    major, minor = torch.cuda.get_device_capability()
    return torch.bfloat16 if major >= 8 else torch.float16

COMPUTE_DTYPE = pick_compute_dtype()
print("GPU:", torch.cuda.get_device_name(0))
print("Compute dtype:", COMPUTE_DTYPE)

# -------------------------
# 1) Upload CSV
# -------------------------
print("Upload your CSV (must include 'Sentence' and 'Condition' columns)")
uploaded = files.upload()
if not uploaded:
    raise RuntimeError("No file uploaded.")
CSV_PATH = list(uploaded.keys())[0]
print("Using:", CSV_PATH)

# -------------------------
# 2) Config
# -------------------------
MODEL_NAME = "Orbina/Orbita-v0.1"
OUT_PATH = "lm_logprob_results_high_low_orbita_v0_1_c_and_f_nopunct.csv"

SENT_COL = "Sentence"
COND_COL = "Condition"

FILTER_TO_HIGH_LOW = True
STRICT_VERB_MAP = False  # True => skip items whose last_word isn't in VERB_MAP
LOAD_IN_4BIT = True

# -------------------------
# 3) Verb map (UPDATED to the new big map)
# -------------------------
VERB_MAP = {
    "alımlar": ("başladı", "başlamış"),
    "antibiyotikler": ("tükendi", "tükenmiş"),
    "ataması": ("açıklandı", "açıklanmış"),
    "bakiyesi": ("bitti", "bitmiş"),
    "bankacılık": ("düzeldi", "düzelmiş"),
    "baskı": ("geldi", "gelmiş"),
    "basıncı": ("düştü", "düşmüş"),
    "belli": ("oldu", "olmuş"),
    "biletleri": ("tükendi", "tükenmiş"),
    "bölümü": ("sızdı", "sızmış"),
    "dağıtıma": ("çıktı", "çıkmış"),
    "değişimi": ("onaylandı", "onaylanmış"),
    "dosyalar": ("silindi", "silinmiş"),
    "durumu": ("değişti", "değişmiş"),
    "dün": ("başladı", "başlamış"),
    "ekip": ("büyüdü", "büyümüş"),
    "elektrikleri": ("kesildi", "kesilmiş"),
    "fiyatı": ("arttı", "artmış"),
    "fırtına": ("başladı", "başlamış"),
    "geri": ("çekildi", "çekilmiş"),
    "görüşmelere": ("başlandı", "başlanmış"),
    "gözetmenleri": ("değişti", "değişmiş"),
    "gücü": ("azaltıldı", "azaltılmış"),
    "hata": ("düzeltildi", "düzeltilmiş"),
    "hesaplar": ("kilitlendi", "kilitlenmiş"),
    "ihaleyi": ("kazandı", "kazanmış"),
    "ilan": ("edildi", "edilmiş"),
    "ilaçlama": ("yapıldı", "yapılmış"),
    "indirim": ("uzadı", "uzamış"),
    "indirimler": ("başladı", "başlamış"),
    "internet": ("gitti", "gitmiş"),
    "iptal": ("edildi", "edilmiş"),
    "istifa": ("etti", "etmiş"),
    "istifası": ("duyuruldu", "duyurulmuş"),
    "işlemcisini": ("değiştirdi", "değiştirmiş"),
    "kadro": ("netleşti", "netleşmiş"),
    "kapılar": ("açıldı", "açılmış"),
    "kart": ("çıktı", "çıkmış"),
    "kayıtları": ("uzatıldı", "uzatılmış"),
    "kesintisi": ("başladı", "başlamış"),
    "kullanımı": ("yasaklandı", "yasaklanmış"),
    "maaşlar": ("yattı", "yatmış"),
    "noktaları": ("kaldırıldı", "kaldırılmış"),
    "oranı": ("yükseldi", "yükselmiş"),
    "otobüsü": ("kalktı", "kalkmış"),
    "payı": ("arttı", "artmış"),
    "perona": ("girdi", "girmiş"),
    "primler": ("yatırıldı", "yatırılmış"),
    "programı": ("açıklandı", "açıklanmış"),
    "projesi": ("onaylandı", "onaylanmış"),
    "randevuları": ("açıldı", "açılmış"),
    "raporu": ("yayınlandı", "yayınlanmış"),
    "rötar": ("yaptı", "yapmış"),
    "saati": ("değişti", "değişmiş"),
    "saatleri": ("değişti", "değişmiş"),
    "sakatlığı": ("uzadı", "uzamış"),
    "sanatçı": ("gelmedi", "gelmemiş"),
    "sarsıntılar": ("azaldı", "azalmış"),
    "sayım": ("başladı", "başlamış"),
    "seansı": ("eklendi", "eklenmiş"),
    "seferler": ("aksadı", "aksamış"),
    "sonuçları": ("açıklandı", "açıklanmış"),
    "stokları": ("bitti", "bitmiş"),
    "stoğu": ("geldi", "gelmiş"),
    "sular": ("kesildi", "kesilmiş"),
    "sunucular": ("çöktü", "çökmüş"),
    "sınav": ("ertelendi", "ertelenmiş"),
    "sınıfı": ("değişti", "değişmiş"),
    "tarihe": ("ertelendi", "ertelenmiş"),
    "tarihi": ("ertelendi", "ertelenmiş"),
    "trafiğe": ("kapandı", "kapanmış"),
    "tünel": ("kapatıldı", "kapatılmış"),
    "uygulama": ("güncellendi", "güncellenmiş"),
    "uçağı": ("gecikti", "gecikmiş"),
    "yasağı": ("kalktı", "kalkmış"),
    "yayın": ("açıldı", "açılmış"),
    "yağışı": ("yaklaştı", "yaklaşmış"),
    "zam": ("geldi", "gelmiş"),
    "zorunluluğu": ("kalktı", "kalkmış"),
    "özellik": ("geldi", "gelmiş"),
    "ücreti": ("arttı", "artmış"),
    "ücretleri": ("arttı", "artmış"),
}

# -------------------------
# 4) Helpers
# -------------------------
def split_on_blank(sentence: str):
    s = str(sentence)
    m = re.search(r"_{2,}", s)  # blank = __ or longer
    if not m:
        return None, None
    return s[:m.start()], s[m.end():]

def _clean_last_word(pre_text: str) -> str:
    clean = re.sub(r"[^\w\s]", "", str(pre_text)).strip()
    if not clean:
        return ""
    return clean.split()[-1].lower()

def get_candidates_from_verbmap(prompt_left: str):
    last_word = _clean_last_word(prompt_left)
    if last_word in VERB_MAP:
        c1, c2 = VERB_MAP[last_word]
        return c1, c2, last_word, True
    return "edildi", "edilmiş", last_word, False

def insert_candidate(prompt_left: str, candidate: str) -> str:
    candidate = str(candidate).strip()
    if prompt_left and not prompt_left.endswith((" ", "\t", "\n")):
        return " " + candidate
    return candidate

def choice_from_delta(delta: float) -> str:
    if delta > 0: return "DI"
    if delta < 0: return "MIŞ"
    return "TIE"

def _shift_trailing_ws(prompt: str, continuation: str):
    m = re.search(r"\s*$", prompt)
    trail = m.group(0) if m else ""
    if trail:
        return prompt[:-len(trail)], trail + continuation
    return prompt, continuation

def strip_leading_punct(s: str) -> str:
    # remove leading punctuation and surrounding whitespace
    return re.sub(r"^\s*[.?!,;:]+\s*", "", str(s))

def attach_suffix_no_punct(continuation: str, suffix_right: str) -> str:
    suf = strip_leading_punct(suffix_right).strip()
    if not suf:
        return continuation
    return continuation + " " + suf

# -------------------------
# 5) Load model + tokenizer
# -------------------------
print("Loading model:", MODEL_NAME)

try:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True, trust_remote_code=True)
except Exception as e:
    print("Fast tokenizer failed, falling back to slow tokenizer. Error:", repr(e))
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=False, trust_remote_code=True)

if tokenizer.pad_token is None and tokenizer.eos_token is not None:
    tokenizer.pad_token = tokenizer.eos_token

load_kwargs = dict(
    device_map="auto",
    torch_dtype=COMPUTE_DTYPE,
    low_cpu_mem_usage=True,
)

if LOAD_IN_4BIT:
    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=COMPUTE_DTYPE,
    )
    load_kwargs["quantization_config"] = quant_config

model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, trust_remote_code=True, **load_kwargs)
model.eval()

MODEL_DEVICE = next(model.parameters()).device
print("Model loaded.")
print("4-bit:", LOAD_IN_4BIT)
print("Model device:", MODEL_DEVICE)

# -------------------------
# 6) Logprob
# -------------------------
@torch.inference_mode()
def logprob_continuation(prompt: str, continuation: str):
    """
    Returns: sum_logp, mean_logp, n_tokens, prefix_ok
    Scores EXACT prompt+continuation.
    """
    prompt2, cont2 = _shift_trailing_ws(prompt, continuation)
    full = prompt2 + cont2

    enc_full = tokenizer(full, return_tensors="pt", add_special_tokens=False)
    enc_prompt = tokenizer(prompt2, return_tensors="pt", add_special_tokens=False)

    full_ids = enc_full.input_ids[0]
    prompt_ids = enc_prompt.input_ids[0]
    prefix_ok = bool(torch.equal(full_ids[:len(prompt_ids)], prompt_ids))

    prompt_len = len(prompt_ids)
    cont_ids = full_ids[prompt_len:]
    n = len(cont_ids)
    if n == 0 or prompt_len == 0:
        return float("-inf"), float("-inf"), 0, prefix_ok

    input_ids = enc_full.input_ids.to(MODEL_DEVICE)
    attention_mask = enc_full.attention_mask.to(MODEL_DEVICE)

    logits = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False).logits[0]
    logprobs = F.log_softmax(logits, dim=-1)

    start = prompt_len - 1
    end = start + n
    lp_slice = logprobs[start:end]

    cont_ids_dev = cont_ids.to(MODEL_DEVICE)
    token_logps = lp_slice.gather(1, cont_ids_dev.unsqueeze(1)).squeeze(1)

    sum_logp = float(token_logps.sum().item())
    mean_logp = sum_logp / n
    return sum_logp, mean_logp, n, prefix_ok

def score_item(prompt_left: str, suffix_right: str, cand_di: str, cand_mis: str):
    """
    c: candidate-only (primary)
    f: candidate+suffix with leading punctuation removed (robustness)
    """
    di_ins = insert_candidate(prompt_left, cand_di)
    mis_ins = insert_candidate(prompt_left, cand_mis)

    # c) candidate-only
    di_c_sum, di_c_mean, di_c_n, di_c_ok = logprob_continuation(prompt_left, di_ins)
    mi_c_sum, mi_c_mean, mi_c_n, mi_c_ok = logprob_continuation(prompt_left, mis_ins)

    # f) candidate + suffix (no leading punctuation)
    suffix_stripped = strip_leading_punct(suffix_right)
    di_full = attach_suffix_no_punct(di_ins, suffix_right)
    mi_full = attach_suffix_no_punct(mis_ins, suffix_right)

    di_f_sum, di_f_mean, di_f_n, di_f_ok = logprob_continuation(prompt_left, di_full)
    mi_f_sum, mi_f_mean, mi_f_n, mi_f_ok = logprob_continuation(prompt_left, mi_full)

    delta_c_mean = di_c_mean - mi_c_mean
    delta_f_mean = di_f_mean - mi_f_mean

    return {
        "Used_Insert_DI": di_ins,
        "Used_Insert_MIS": mis_ins,
        "suffix_right_stripped": suffix_stripped,

        "di_c_sum": di_c_sum, "di_c_mean": di_c_mean, "di_c_n_tok": di_c_n, "di_c_prefix_ok": di_c_ok,
        "mis_c_sum": mi_c_sum, "mis_c_mean": mi_c_mean, "mis_c_n_tok": mi_c_n, "mis_c_prefix_ok": mi_c_ok,
        "delta_c_sum": di_c_sum - mi_c_sum,
        "delta_c_mean": delta_c_mean,
        "choice_c_mean": choice_from_delta(delta_c_mean),

        "di_f_sum": di_f_sum, "di_f_mean": di_f_mean, "di_f_n_tok": di_f_n, "di_f_prefix_ok": di_f_ok,
        "mis_f_sum": mi_f_sum, "mis_f_mean": mi_f_mean, "mis_f_n_tok": mi_f_n, "mis_f_prefix_ok": mi_f_ok,
        "delta_f_sum": di_f_sum - mi_f_sum,
        "delta_f_mean": delta_f_mean,
        "choice_f_mean": choice_from_delta(delta_f_mean),
    }

# -------------------------
# 7) Read CSV + filter
# -------------------------
df = pd.read_csv(CSV_PATH)
if SENT_COL not in df.columns or COND_COL not in df.columns:
    raise ValueError(f"CSV must contain '{SENT_COL}' and '{COND_COL}' columns.")

df[COND_COL] = df[COND_COL].astype(str).str.strip()

if FILTER_TO_HIGH_LOW:
    df = df[df[COND_COL].str.lower().isin(["high", "low"])].reset_index(drop=True)
    df[COND_COL] = df[COND_COL].str.capitalize()

print("Rows to score:", len(df))

# Coverage check on High/Low
missing_keys = []
for s in df[SENT_COL].astype(str):
    left, _ = split_on_blank(s)
    if left is None:
        continue
    lw = _clean_last_word(left)
    if lw and lw not in VERB_MAP:
        missing_keys.append(lw)

if missing_keys:
    print("\nWARNING: Some last_word values are not in VERB_MAP:")
    print(pd.Series(missing_keys).value_counts())
else:
    print("\nOK: VERB_MAP covers High/Low items.")

# -------------------------
# 8) Loop
# -------------------------
results = []
skipped_no_blank = 0
skipped_no_map = 0

for i, row in df.iterrows():
    sent = row[SENT_COL]
    cond = row.get(COND_COL, "Unknown")

    left, right = split_on_blank(sent)
    if left is None:
        skipped_no_blank += 1
        continue

    cand_di, cand_mis, last_word, map_hit = get_candidates_from_verbmap(left)
    if STRICT_VERB_MAP and (not map_hit):
        skipped_no_map += 1
        continue

    sc = score_item(left, right, cand_di, cand_mis)

    results.append({
        "row_id": i,
        "Condition": cond,
        "Sentence_raw": str(sent),
        "prompt_left": left,
        "suffix_right_raw": right,
        "last_word": last_word,
        "verb_map_hit": map_hit,
        "Used_Verb_DI": cand_di,
        "Used_Verb_MIS": cand_mis,
        **sc
    })

out_df = pd.DataFrame(results)
out_df.to_csv(OUT_PATH, index=False, encoding="utf-8-sig")

print("\nDone. Saved:", OUT_PATH)
print("Skipped (no blank):", skipped_no_blank)
print("Skipped (no map; STRICT_VERB_MAP=True):", skipped_no_map)

# -------------------------
# 9) Summary
# -------------------------
print("\n== Mean deltas by Condition ==")
print(out_df.groupby("Condition")[["delta_c_mean", "delta_f_mean"]].mean())

print("\n== Choice counts (candidate-only) ==")
print(out_df.groupby("Condition")["choice_c_mean"].value_counts())

print("\n== Choice counts (candidate+suffix, NO leading punct) ==")
print(out_df.groupby("Condition")["choice_f_mean"].value_counts())

g = out_df.groupby("Condition")[["delta_c_mean", "delta_f_mean"]].mean()
if ("High" in g.index) and ("Low" in g.index):
    print("\n*** TRUST EFFECT (High - Low) ***")
    print(f"candidate-only            (delta_c_mean): {g.loc['High','delta_c_mean'] - g.loc['Low','delta_c_mean']:.4f}")
    print(f"candidate+suffix NO PUNCT (delta_f_mean): {g.loc['High','delta_f_mean'] - g.loc['Low','delta_f_mean']:.4f}")

prefix_cols = ["di_c_prefix_ok","mis_c_prefix_ok","di_f_prefix_ok","mis_f_prefix_ok"]
mismatch_rate = 1.0 - out_df[prefix_cols].astype(bool).mean()
print("\n== Prefix mismatch rates (should be near 0) ==")
print(mismatch_rate)

# -------------------------
# 10) Download output
# -------------------------
files.download(OUT_PATH)

# =========================
# ONE-CELL COLAB (GATED): DI vs MIŞ scoring with TURKCELL/Turkcell-LLM-7b-v1 (Transformers + 4-bit + HF auth)
# MOST SCIENTIFIC VERSION:
#   - c = candidate-only (primary; DI vs MIŞ on the verb itself)
#   - f = candidate + suffix_right with LEADING PUNCTUATION REMOVED (so '.' is never scored)
#   - If suffix_right is only '.', then f == c (sanity check)
# =========================

# ---- 0) Install ----
!pip -q install -U "transformers>=4.50.0" accelerate bitsandbytes sentencepiece "pandas==2.2.2" huggingface_hub

# Set allocator BEFORE torch uses CUDA (helps prevent tiny-alloc OOM)
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True,max_split_size_mb:256"

import re
import getpass
import torch
import torch.nn.functional as F
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from huggingface_hub import login
from google.colab import files

# -------------------------
# 1) GPU check
# -------------------------
if not torch.cuda.is_available():
    raise RuntimeError("No GPU detected. In Colab: Runtime > Change runtime type > GPU, then re-run.")

props = torch.cuda.get_device_properties(0)
total_gb = props.total_memory / (1024**3)
print("GPU:", props.name)
print("GPU VRAM (GiB):", round(total_gb, 2))
major, minor = torch.cuda.get_device_capability()
print("Compute capability:", (major, minor))
torch.backends.cuda.matmul.allow_tf32 = True

def pick_compute_dtype():
    major, _ = torch.cuda.get_device_capability()
    return torch.bfloat16 if major >= 8 else torch.float16

COMPUTE_DTYPE = pick_compute_dtype()
print("Compute dtype:", COMPUTE_DTYPE)

# Keep headroom to avoid tiny-alloc OOM
gpu_budget = max(int(total_gb - (6 if total_gb <= 24 else 4)), 10)
MAX_MEMORY = {0: f"{gpu_budget}GiB", "cpu": "240GiB"}
print("max_memory:", MAX_MEMORY)

# -------------------------
# 2) HF auth (gated model)
#   - Tries Colab Secret HF_TOKEN if present
#   - Otherwise prompts once
# -------------------------
HF_TOKEN = None
try:
    from google.colab import userdata
    HF_TOKEN = userdata.get("HF_TOKEN")
except Exception:
    HF_TOKEN = None

if not HF_TOKEN:
    HF_TOKEN = getpass.getpass("Paste your HF token (hf_...): ")

# Login so *all* hub requests are authenticated (token also passed explicitly below)
login(token=HF_TOKEN)

# -------------------------
# 3) Upload CSV
# -------------------------
print("\nUpload your CSV (must include 'Sentence' and 'Condition' columns)")
uploaded = files.upload()
if not uploaded:
    raise RuntimeError("No file uploaded.")
CSV_PATH = list(uploaded.keys())[0]
print("Using:", CSV_PATH)

# -------------------------
# 4) Config
# -------------------------
MODEL_NAME = "TURKCELL/Turkcell-LLM-7b-v1"  # <<< TURKCELL MODEL
OUT_PATH = "lm_logprob_results_high_low_turkcell_llm_7b_v1_c_and_f_nopunct.csv"

SENT_COL = "Sentence"
COND_COL = "Condition"
FILTER_TO_HIGH_LOW = True
STRICT_VERB_MAP = False  # True => skip items whose last_word isn't in VERB_MAP
LOAD_IN_4BIT = True

# -------------------------
# 5) Verb map (UPDATED for 100-per-condition set)
# -------------------------
VERB_MAP = {
    "alımlar": ("başladı", "başlamış"),
    "antibiyotikler": ("tükendi", "tükenmiş"),
    "ataması": ("açıklandı", "açıklanmış"),
    "bakiyesi": ("bitti", "bitmiş"),
    "bankacılık": ("düzeldi", "düzelmiş"),
    "baskı": ("geldi", "gelmiş"),
    "basıncı": ("düştü", "düşmüş"),
    "belli": ("oldu", "olmuş"),
    "biletleri": ("tükendi", "tükenmiş"),
    "bölümü": ("sızdı", "sızmış"),
    "dağıtıma": ("çıktı", "çıkmış"),
    "değişimi": ("onaylandı", "onaylanmış"),
    "dosyalar": ("silindi", "silinmiş"),
    "durumu": ("değişti", "değişmiş"),
    "dün": ("başladı", "başlamış"),
    "ekip": ("büyüdü", "büyümüş"),
    "elektrikleri": ("kesildi", "kesilmiş"),
    "fiyatı": ("arttı", "artmış"),
    "fırtına": ("başladı", "başlamış"),
    "geri": ("çekildi", "çekilmiş"),
    "görüşmelere": ("başlandı", "başlanmış"),
    "gözetmenleri": ("değişti", "değişmiş"),
    "gücü": ("azaltıldı", "azaltılmış"),
    "hata": ("düzeltildi", "düzeltilmiş"),
    "hesaplar": ("kilitlendi", "kilitlenmiş"),
    "ihaleyi": ("kazandı", "kazanmış"),
    "ilan": ("edildi", "edilmiş"),
    "ilaçlama": ("yapıldı", "yapılmış"),
    "indirim": ("uzadı", "uzamış"),
    "indirimler": ("başladı", "başlamış"),
    "internet": ("gitti", "gitmiş"),
    "iptal": ("edildi", "edilmiş"),
    "istifa": ("etti", "etmiş"),
    "istifası": ("duyuruldu", "duyurulmuş"),
    "işlemcisini": ("değiştirdi", "değiştirmiş"),
    "kadro": ("netleşti", "netleşmiş"),
    "kapılar": ("açıldı", "açılmış"),
    "kart": ("çıktı", "çıkmış"),
    "kayıtları": ("uzatıldı", "uzatılmış"),
    "kesintisi": ("başladı", "başlamış"),
    "kullanımı": ("yasaklandı", "yasaklanmış"),
    "maaşlar": ("yattı", "yatmış"),
    "noktaları": ("kaldırıldı", "kaldırılmış"),
    "oranı": ("yükseldi", "yükselmiş"),
    "otobüsü": ("kalktı", "kalkmış"),
    "payı": ("arttı", "artmış"),
    "perona": ("girdi", "girmiş"),
    "primler": ("yatırıldı", "yatırılmış"),
    "programı": ("açıklandı", "açıklanmış"),
    "projesi": ("onaylandı", "onaylanmış"),
    "randevuları": ("açıldı", "açılmış"),
    "raporu": ("yayınlandı", "yayınlanmış"),
    "rötar": ("yaptı", "yapmış"),
    "saati": ("değişti", "değişmiş"),
    "saatleri": ("değişti", "değişmiş"),
    "sakatlığı": ("uzadı", "uzamış"),
    "sanatçı": ("gelmedi", "gelmemiş"),
    "sarsıntılar": ("azaldı", "azalmış"),
    "sayım": ("başladı", "başlamış"),
    "seansı": ("eklendi", "eklenmiş"),
    "seferler": ("aksadı", "aksamış"),
    "sonuçları": ("açıklandı", "açıklanmış"),
    "stokları": ("bitti", "bitmiş"),
    "stoğu": ("geldi", "gelmiş"),
    "sular": ("kesildi", "kesilmiş"),
    "sunucular": ("çöktü", "çökmüş"),
    "sınav": ("ertelendi", "ertelenmiş"),
    "sınıfı": ("değişti", "değişmiş"),
    "tarihe": ("ertelendi", "ertelenmiş"),
    "tarihi": ("ertelendi", "ertelenmiş"),
    "trafiğe": ("kapandı", "kapanmış"),
    "tünel": ("kapatıldı", "kapatılmış"),
    "uygulama": ("güncellendi", "güncellenmiş"),
    "uçağı": ("gecikti", "gecikmiş"),
    "yasağı": ("kalktı", "kalkmış"),
    "yayın": ("açıldı", "açılmış"),
    "yağışı": ("yaklaştı", "yaklaşmış"),
    "zam": ("geldi", "gelmiş"),
    "zorunluluğu": ("kalktı", "kalkmış"),
    "özellik": ("geldi", "gelmiş"),
    "ücreti": ("arttı", "artmış"),
    "ücretleri": ("arttı", "artmış"),
}

# -------------------------
# 6) Helpers
# -------------------------
def split_on_blank(sentence: str):
    s = str(sentence)
    m = re.search(r"_{2,}", s)  # blank = __ or longer
    if not m:
        return None, None
    return s[:m.start()], s[m.end():]

def _clean_last_word(pre_text: str) -> str:
    clean = re.sub(r"[^\w\s]", "", str(pre_text)).strip()
    if not clean:
        return ""
    return clean.split()[-1].lower()

def get_candidates_from_verbmap(prompt_left: str):
    last_word = _clean_last_word(prompt_left)
    if last_word in VERB_MAP:
        c1, c2 = VERB_MAP[last_word]
        return c1, c2, last_word, True
    return "edildi", "edilmiş", last_word, False

def insert_candidate(prompt_left: str, candidate: str) -> str:
    candidate = str(candidate).strip()
    if prompt_left and not prompt_left.endswith((" ", "\t", "\n")):
        return " " + candidate
    return candidate

def choice_from_delta(delta: float) -> str:
    if delta > 0: return "DI"
    if delta < 0: return "MIŞ"
    return "TIE"

def _shift_trailing_ws(prompt: str, continuation: str):
    m = re.search(r"\s*$", prompt)
    trail = m.group(0) if m else ""
    if trail:
        return prompt[:-len(trail)], trail + continuation
    return prompt, continuation

def strip_leading_punct(s: str) -> str:
    return re.sub(r"^\s*[.?!,;:]+\s*", "", str(s))

def attach_suffix_no_punct(continuation: str, suffix_right: str) -> str:
    suf = strip_leading_punct(suffix_right).strip()
    if not suf:
        return continuation
    return continuation + " " + suf

# -------------------------
# 7) Load tokenizer + model (4-bit) with explicit token
# -------------------------
print("\nLoading model:", MODEL_NAME)
os.makedirs("offload", exist_ok=True)

# Tokenizer (token passed explicitly)
try:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, token=HF_TOKEN, use_fast=True)
except Exception as e:
    print("Fast tokenizer failed, falling back to slow tokenizer. Error:", repr(e))
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, token=HF_TOKEN, use_fast=False)

# Ensure pad token exists
if tokenizer.pad_token is None and tokenizer.eos_token is not None:
    tokenizer.pad_token = tokenizer.eos_token

load_kwargs = dict(
    device_map="auto",
    low_cpu_mem_usage=True,
    max_memory=MAX_MEMORY,
    offload_folder="offload",
    offload_state_dict=True,
    attn_implementation="sdpa",  # avoids flash-attn dependency
)

if LOAD_IN_4BIT:
    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=COMPUTE_DTYPE,
    )
    load_kwargs["quantization_config"] = quant_config
    load_kwargs["torch_dtype"] = COMPUTE_DTYPE
else:
    load_kwargs["torch_dtype"] = COMPUTE_DTYPE

# IMPORTANT: token passed explicitly here too
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, token=HF_TOKEN, **load_kwargs)
model.eval()

MODEL_DEVICE = next(model.parameters()).device
print("Model loaded.")
print("4-bit:", LOAD_IN_4BIT)
print("Model device:", MODEL_DEVICE)

# -------------------------
# 8) Logprob
# -------------------------
@torch.inference_mode()
def logprob_continuation(prompt: str, continuation: str):
    """
    Returns: sum_logp, mean_logp, n_tokens, prefix_ok
    Scores EXACT prompt+continuation.
    """
    prompt2, cont2 = _shift_trailing_ws(prompt, continuation)
    full = prompt2 + cont2

    enc_full = tokenizer(full, return_tensors="pt", add_special_tokens=False)
    enc_prompt = tokenizer(prompt2, return_tensors="pt", add_special_tokens=False)

    full_ids = enc_full.input_ids[0]
    prompt_ids = enc_prompt.input_ids[0]
    prefix_ok = bool(torch.equal(full_ids[:len(prompt_ids)], prompt_ids))

    prompt_len = len(prompt_ids)
    cont_ids = full_ids[prompt_len:]
    n = len(cont_ids)
    if n == 0 or prompt_len == 0:
        return float("-inf"), float("-inf"), 0, prefix_ok

    input_ids = enc_full.input_ids.to(MODEL_DEVICE)
    attention_mask = enc_full.attention_mask.to(MODEL_DEVICE)

    logits = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False).logits[0]
    logprobs = F.log_softmax(logits, dim=-1)

    start = prompt_len - 1
    end = start + n
    lp_slice = logprobs[start:end]

    cont_ids_dev = cont_ids.to(MODEL_DEVICE)
    token_logps = lp_slice.gather(1, cont_ids_dev.unsqueeze(1)).squeeze(1)

    sum_logp = float(token_logps.sum().item())
    mean_logp = sum_logp / n
    return sum_logp, mean_logp, n, prefix_ok

def score_item(prompt_left: str, suffix_right: str, cand_di: str, cand_mis: str):
    """
    c: candidate-only (primary)
    f: candidate+suffix with leading punctuation removed (robustness)
    """
    di_ins = insert_candidate(prompt_left, cand_di)
    mis_ins = insert_candidate(prompt_left, cand_mis)

    # c) candidate-only
    di_c_sum, di_c_mean, di_c_n, di_c_ok = logprob_continuation(prompt_left, di_ins)
    mi_c_sum, mi_c_mean, mi_c_n, mi_c_ok = logprob_continuation(prompt_left, mis_ins)

    # f) candidate + suffix (no leading punctuation)
    suffix_stripped = strip_leading_punct(suffix_right)
    di_full = attach_suffix_no_punct(di_ins, suffix_right)
    mi_full = attach_suffix_no_punct(mis_ins, suffix_right)

    di_f_sum, di_f_mean, di_f_n, di_f_ok = logprob_continuation(prompt_left, di_full)
    mi_f_sum, mi_f_mean, mi_f_n, mi_f_ok = logprob_continuation(prompt_left, mi_full)

    delta_c_mean = di_c_mean - mi_c_mean
    delta_f_mean = di_f_mean - mi_f_mean

    return {
        "Used_Insert_DI": di_ins,
        "Used_Insert_MIS": mis_ins,
        "suffix_right_stripped": suffix_stripped,

        "di_c_sum": di_c_sum, "di_c_mean": di_c_mean, "di_c_n_tok": di_c_n, "di_c_prefix_ok": di_c_ok,
        "mis_c_sum": mi_c_sum, "mis_c_mean": mi_c_mean, "mis_c_n_tok": mi_c_n, "mis_c_prefix_ok": mi_c_ok,
        "delta_c_sum": di_c_sum - mi_c_sum,
        "delta_c_mean": delta_c_mean,
        "choice_c_mean": choice_from_delta(delta_c_mean),

        "di_f_sum": di_f_sum, "di_f_mean": di_f_mean, "di_f_n_tok": di_f_n, "di_f_prefix_ok": di_f_ok,
        "mis_f_sum": mi_f_sum, "mis_f_mean": mi_f_mean, "mis_f_n_tok": mi_f_n, "mis_f_prefix_ok": mi_f_ok,
        "delta_f_sum": di_f_sum - mi_f_sum,
        "delta_f_mean": delta_f_mean,
        "choice_f_mean": choice_from_delta(delta_f_mean),
    }

# -------------------------
# 9) Read CSV + filter
# -------------------------
df = pd.read_csv(CSV_PATH)
if SENT_COL not in df.columns or COND_COL not in df.columns:
    raise ValueError(f"CSV must contain '{SENT_COL}' and '{COND_COL}' columns.")

df[COND_COL] = df[COND_COL].astype(str).str.strip()

if FILTER_TO_HIGH_LOW:
    df = df[df[COND_COL].str.lower().isin(["high", "low"])].reset_index(drop=True)
    df[COND_COL] = df[COND_COL].str.capitalize()

print("\nRows to score:", len(df))

# VERB_MAP coverage check
missing_keys = []
for s in df[SENT_COL].astype(str):
    left, _ = split_on_blank(s)
    if left is None:
        continue
    lw = _clean_last_word(left)
    if lw and lw not in VERB_MAP:
        missing_keys.append(lw)

if missing_keys:
    print("\nWARNING: Some last_word values are not in VERB_MAP:")
    print(pd.Series(missing_keys).value_counts())
else:
    print("\nOK: VERB_MAP covers High/Low items.")

# -------------------------
# 10) Loop
# -------------------------
results = []
skipped_no_blank = 0
skipped_no_map = 0

for i, row in df.iterrows():
    sent = row[SENT_COL]
    cond = row.get(COND_COL, "Unknown")

    left, right = split_on_blank(sent)
    if left is None:
        skipped_no_blank += 1
        continue

    cand_di, cand_mis, last_word, map_hit = get_candidates_from_verbmap(left)
    if STRICT_VERB_MAP and (not map_hit):
        skipped_no_map += 1
        continue

    sc = score_item(left, right, cand_di, cand_mis)

    results.append({
        "row_id": i,
        "Condition": cond,
        "Sentence_raw": str(sent),
        "prompt_left": left,
        "suffix_right_raw": right,
        "last_word": last_word,
        "verb_map_hit": map_hit,
        "Used_Verb_DI": cand_di,
        "Used_Verb_MIS": cand_mis,
        **sc
    })

out_df = pd.DataFrame(results)
out_df.to_csv(OUT_PATH, index=False, encoding="utf-8-sig")

print("\nDone. Saved:", OUT_PATH)
print("Skipped (no blank):", skipped_no_blank)
print("Skipped (no map; STRICT_VERB_MAP=True):", skipped_no_map)

# -------------------------
# 11) Summary
# -------------------------
print("\n== Mean deltas by Condition ==")
print(out_df.groupby("Condition")[["delta_c_mean", "delta_f_mean"]].mean())

print("\n== Choice counts (candidate-only) ==")
print(out_df.groupby("Condition")["choice_c_mean"].value_counts())

print("\n== Choice counts (candidate+suffix, NO leading punct) ==")
print(out_df.groupby("Condition")["choice_f_mean"].value_counts())

g = out_df.groupby("Condition")[["delta_c_mean", "delta_f_mean"]].mean()
if ("High" in g.index) and ("Low" in g.index):
    print("\n*** TRUST EFFECT (High - Low) ***")
    print(f"candidate-only            (delta_c_mean): {g.loc['High','delta_c_mean'] - g.loc['Low','delta_c_mean']:.4f}")
    print(f"candidate+suffix NO PUNCT (delta_f_mean): {g.loc['High','delta_f_mean'] - g.loc['Low','delta_f_mean']:.4f}")

prefix_cols = ["di_c_prefix_ok","mis_c_prefix_ok","di_f_prefix_ok","mis_f_prefix_ok"]
mismatch_rate = 1.0 - out_df[prefix_cols].astype(bool).mean()
print("\n== Prefix mismatch rates (should be near 0) ==")
print(mismatch_rate)

# -------------------------
# 12) Download output
# -------------------------
files.download(OUT_PATH)